name: Build Docker
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: [gcp-runner]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Configure outputs
        run: echo "SHORT_SHA=${{ github.sha }}" >> $GITHUB_ENV
      - name: DEBUG
        run: echo "${SHORT_SHA}" && ls -lah
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to jFrog registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: "emiliocastro.jfrog.io/default-docker-virtual/nginx-demo:${SHORT_SHA}"
  webhook:
    name: Redeploy webhook call
    runs-on: [gcp-runner]
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          body: "{ 'short-sha': ${SHORT_SHA} }"
